apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: microservices
type: Opaque
stringData:
  MYSQL_USER: "user"
  MYSQL_PASSWORD: "secret"
  MYSQL_ROOT_PASSWORD: "rootsecret"
  GF_SECURITY_ADMIN_USER: "admin"
  GF_SECURITY_ADMIN_PASSWORD: "admin123"
